# Generated by Django 3.2 on 2021-05-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authJSON', '0003_jsondata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jsondata',
            table='json',
        ),
    ]
