# Generated by Django 3.2 on 2021-05-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authJSON', '0004_alter_jsondata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jsondata',
            table=None,
        ),
    ]
